api.baseUrl=https://postman-echo.com
http.connectTimeoutMs=5000
http.readTimeoutMs=15000
http.retry.maxAttempts=1
http.retry.delayMs=0
oauth2.refreshSkewSeconds=30

auth.basic.usernameSecretKey=auth.basic.username
auth.basic.passwordSecretKey=auth.basic.password

auth.oauth2.tokenUrl=https://auth.dev.local/oauth/token
auth.oauth2.clientId=dev-client
auth.oauth2.clientSecretKey=auth.oauth2.clientSecret
auth.oauth2.username=dev-user
auth.oauth2.passwordSecretKey=auth.oauth2.password
auth.oauth2.scope=openid profile
